# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BCQualityCheck.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BCQualityCheck(object):
    def setupUi(self, BCQualityCheck):
        BCQualityCheck.setObjectName("BCQualityCheck")
        BCQualityCheck.setEnabled(True)
        BCQualityCheck.resize(1097, 690)
        BCQualityCheck.setMinimumSize(QtCore.QSize(1097, 690))
        BCQualityCheck.setMaximumSize(QtCore.QSize(1097, 690))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        BCQualityCheck.setFont(font)
        self.groupBox = QtWidgets.QGroupBox(BCQualityCheck)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 251, 130))
        self.groupBox.setMinimumSize(QtCore.QSize(251, 130))
        self.groupBox.setMaximumSize(QtCore.QSize(251, 130))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(120, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(120, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(50, 40, 61, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 40, 71, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 70, 61, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 70, 71, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_49 = QtWidgets.QLabel(self.groupBox)
        self.label_49.setGeometry(QtCore.QRect(10, 100, 231, 20))
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.groupBox_2 = QtWidgets.QGroupBox(BCQualityCheck)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 170, 391, 221))
        self.groupBox_2.setMinimumSize(QtCore.QSize(391, 221))
        self.groupBox_2.setMaximumSize(QtCore.QSize(391, 221))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(30, 130, 331, 71))
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 40, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 80, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 40, 111, 23))
        self.pushButton_4.setAutoExclusive(False)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(270, 80, 111, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_3 = QtWidgets.QGroupBox(BCQualityCheck)
        self.groupBox_3.setGeometry(QtCore.QRect(450, 20, 291, 651))
        self.groupBox_3.setMinimumSize(QtCore.QSize(291, 651))
        self.groupBox_3.setMaximumSize(QtCore.QSize(291, 651))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(30, 80, 71, 21))
        self.label_10.setAutoFillBackground(True)
        self.label_10.setTextFormat(QtCore.Qt.RichText)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(30, 120, 71, 21))
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(30, 160, 71, 21))
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(30, 200, 71, 21))
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(30, 240, 71, 21))
        self.label_14.setTextFormat(QtCore.Qt.RichText)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(30, 280, 71, 21))
        self.label_15.setTextFormat(QtCore.Qt.RichText)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(30, 320, 71, 21))
        self.label_16.setTextFormat(QtCore.Qt.RichText)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(30, 360, 71, 21))
        self.label_17.setTextFormat(QtCore.Qt.RichText)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(30, 400, 71, 21))
        self.label_18.setTextFormat(QtCore.Qt.RichText)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(30, 440, 71, 21))
        self.label_19.setTextFormat(QtCore.Qt.RichText)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(30, 480, 71, 21))
        self.label_20.setTextFormat(QtCore.Qt.RichText)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(30, 520, 71, 21))
        self.label_21.setTextFormat(QtCore.Qt.RichText)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(30, 560, 71, 21))
        self.label_22.setTextFormat(QtCore.Qt.RichText)
        self.label_22.setObjectName("label_22")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(110, 80, 113, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(110, 120, 113, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(110, 160, 113, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(110, 200, 113, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(110, 240, 113, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(110, 280, 113, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_15.setGeometry(QtCore.QRect(110, 320, 113, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_16.setGeometry(QtCore.QRect(110, 360, 113, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_17.setGeometry(QtCore.QRect(110, 400, 113, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_18.setGeometry(QtCore.QRect(110, 440, 113, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_19.setGeometry(QtCore.QRect(110, 480, 113, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_20.setGeometry(QtCore.QRect(110, 520, 113, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_21.setGeometry(QtCore.QRect(110, 560, 113, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.groupBox_4 = QtWidgets.QGroupBox(BCQualityCheck)
        self.groupBox_4.setGeometry(QtCore.QRect(770, 20, 311, 651))
        self.groupBox_4.setMinimumSize(QtCore.QSize(311, 651))
        self.groupBox_4.setMaximumSize(QtCore.QSize(311, 651))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(30, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setTextFormat(QtCore.Qt.RichText)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(30, 120, 101, 21))
        self.label_24.setTextFormat(QtCore.Qt.RichText)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(30, 160, 101, 21))
        self.label_25.setTextFormat(QtCore.Qt.RichText)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(30, 200, 101, 21))
        self.label_26.setTextFormat(QtCore.Qt.RichText)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(30, 240, 101, 21))
        self.label_27.setTextFormat(QtCore.Qt.RichText)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(30, 280, 101, 21))
        self.label_28.setTextFormat(QtCore.Qt.RichText)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(30, 320, 101, 21))
        self.label_29.setTextFormat(QtCore.Qt.RichText)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(30, 360, 101, 21))
        self.label_30.setTextFormat(QtCore.Qt.RichText)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(30, 400, 101, 21))
        self.label_31.setTextFormat(QtCore.Qt.RichText)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setGeometry(QtCore.QRect(30, 440, 101, 21))
        self.label_32.setTextFormat(QtCore.Qt.RichText)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(30, 480, 101, 21))
        self.label_33.setTextFormat(QtCore.Qt.RichText)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(30, 520, 101, 21))
        self.label_34.setTextFormat(QtCore.Qt.RichText)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        self.label_35.setGeometry(QtCore.QRect(30, 560, 91, 21))
        self.label_35.setTextFormat(QtCore.Qt.RichText)
        self.label_35.setObjectName("label_35")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_22.setGeometry(QtCore.QRect(110, 560, 113, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_23.setEnabled(True)
        self.lineEdit_23.setGeometry(QtCore.QRect(110, 80, 113, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_24.setGeometry(QtCore.QRect(110, 120, 113, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_25.setGeometry(QtCore.QRect(110, 160, 113, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_26.setGeometry(QtCore.QRect(110, 200, 113, 20))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_27.setGeometry(QtCore.QRect(110, 240, 113, 20))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_28.setGeometry(QtCore.QRect(110, 280, 113, 20))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_29.setGeometry(QtCore.QRect(110, 320, 113, 20))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_30.setGeometry(QtCore.QRect(110, 360, 113, 20))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_31.setGeometry(QtCore.QRect(110, 400, 113, 20))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_32.setGeometry(QtCore.QRect(110, 440, 113, 20))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_33.setGeometry(QtCore.QRect(110, 480, 113, 20))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_34.setGeometry(QtCore.QRect(110, 520, 113, 20))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setEnabled(True)
        self.label_36.setGeometry(QtCore.QRect(230, 69, 71, 41))
        self.label_36.setText("")
        self.label_36.setWordWrap(True)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setGeometry(QtCore.QRect(233, 109, 71, 41))
        self.label_37.setText("")
        self.label_37.setWordWrap(True)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_4)
        self.label_38.setGeometry(QtCore.QRect(233, 149, 71, 41))
        self.label_38.setText("")
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        self.label_39.setGeometry(QtCore.QRect(233, 190, 71, 41))
        self.label_39.setText("")
        self.label_39.setWordWrap(True)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_4)
        self.label_40.setGeometry(QtCore.QRect(233, 230, 71, 41))
        self.label_40.setText("")
        self.label_40.setWordWrap(True)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_4)
        self.label_41.setGeometry(QtCore.QRect(233, 270, 71, 41))
        self.label_41.setText("")
        self.label_41.setWordWrap(True)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_4)
        self.label_42.setGeometry(QtCore.QRect(233, 310, 71, 41))
        self.label_42.setText("")
        self.label_42.setWordWrap(True)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_4)
        self.label_43.setGeometry(QtCore.QRect(233, 350, 71, 41))
        self.label_43.setText("")
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox_4)
        self.label_44.setGeometry(QtCore.QRect(233, 389, 71, 41))
        self.label_44.setText("")
        self.label_44.setWordWrap(True)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_4)
        self.label_45.setGeometry(QtCore.QRect(233, 429, 71, 41))
        self.label_45.setText("")
        self.label_45.setWordWrap(True)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_4)
        self.label_46.setGeometry(QtCore.QRect(233, 469, 71, 41))
        self.label_46.setText("")
        self.label_46.setWordWrap(True)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_4)
        self.label_47.setGeometry(QtCore.QRect(233, 509, 71, 41))
        self.label_47.setText("")
        self.label_47.setWordWrap(True)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_4)
        self.label_48.setGeometry(QtCore.QRect(233, 549, 71, 41))
        self.label_48.setText("")
        self.label_48.setWordWrap(True)
        self.label_48.setObjectName("label_48")
        self.groupBox_5 = QtWidgets.QGroupBox(BCQualityCheck)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 420, 391, 251))
        self.groupBox_5.setMinimumSize(QtCore.QSize(391, 251))
        self.groupBox_5.setMaximumSize(QtCore.QSize(391, 251))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(20, 50, 71, 16))
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(20, 100, 81, 16))
        self.label_9.setAutoFillBackground(False)
        self.label_9.setLineWidth(11)
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_7.setGeometry(QtCore.QRect(90, 50, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_8.setGeometry(QtCore.QRect(90, 100, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 50, 41, 23))
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_7.setGeometry(QtCore.QRect(330, 100, 41, 21))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_8.setGeometry(QtCore.QRect(50, 170, 111, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_9.setGeometry(QtCore.QRect(210, 170, 111, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton = QtWidgets.QPushButton(BCQualityCheck)
        self.pushButton.setGeometry(QtCore.QRect(300, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setAutoExclusive(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(BCQualityCheck)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 80, 121, 23))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(BCQualityCheck)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 120, 121, 23))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(BCQualityCheck)
        QtCore.QMetaObject.connectSlotsByName(BCQualityCheck)

    def retranslateUi(self, BCQualityCheck):
        _translate = QtCore.QCoreApplication.translate
        BCQualityCheck.setWindowTitle(_translate("BCQualityCheck", "BCQualityCheck"))
        self.groupBox.setTitle(_translate("BCQualityCheck", "混淆矩阵"))
        self.label.setText(_translate("BCQualityCheck", "TP"))
        self.label_2.setText(_translate("BCQualityCheck", "FN"))
        self.label_3.setText(_translate("BCQualityCheck", "FP"))
        self.label_4.setText(_translate("BCQualityCheck", "TN"))
        self.groupBox_2.setTitle(_translate("BCQualityCheck", "误差阈值(数据质量评估)"))
        self.label_5.setText(_translate("BCQualityCheck", "常规误差阈值"))
        self.label_6.setText(_translate("BCQualityCheck", "Density误差阈值"))
        self.label_7.setText(_translate("BCQualityCheck", "若预测性能与经反算混淆矩阵得到的性能误差大于该阈值，则该组实验数据被视为存在数据质量问题"))
        self.pushButton_4.setText(_translate("BCQualityCheck", "设定变更值"))
        self.pushButton_5.setText(_translate("BCQualityCheck", "恢复默认值"))
        self.groupBox_3.setTitle(_translate("BCQualityCheck", "预测性能 "))
        self.label_10.setText(_translate("BCQualityCheck", "FPR"))
        self.label_11.setText(_translate("BCQualityCheck", "FNR"))
        self.label_12.setText(_translate("BCQualityCheck", "TNR"))
        self.label_13.setText(_translate("BCQualityCheck", "ER"))
        self.label_14.setText(_translate("BCQualityCheck", "Recall"))
        self.label_15.setText(_translate("BCQualityCheck", "Precision"))
        self.label_16.setText(_translate("BCQualityCheck", "Accuracy"))
        self.label_17.setText(_translate("BCQualityCheck", "FMeasure"))
        self.label_18.setText(_translate("BCQualityCheck", "MCC"))
        self.label_19.setText(_translate("BCQualityCheck", "GMeasure"))
        self.label_20.setText(_translate("BCQualityCheck", "GMean"))
        self.label_21.setText(_translate("BCQualityCheck", "Balance"))
        self.label_22.setText(_translate("BCQualityCheck", "Density"))
        self.groupBox_4.setTitle(_translate("BCQualityCheck", "经反算混淆矩阵重新计算后的性能"))
        self.label_23.setText(_translate("BCQualityCheck", "FPR"))
        self.label_24.setText(_translate("BCQualityCheck", "FNR"))
        self.label_25.setText(_translate("BCQualityCheck", "TNR"))
        self.label_26.setText(_translate("BCQualityCheck", "ER"))
        self.label_27.setText(_translate("BCQualityCheck", "Recall"))
        self.label_28.setText(_translate("BCQualityCheck", "Precision"))
        self.label_29.setText(_translate("BCQualityCheck", "Accuracy"))
        self.label_30.setText(_translate("BCQualityCheck", "FMeasure"))
        self.label_31.setText(_translate("BCQualityCheck", "MCC"))
        self.label_32.setText(_translate("BCQualityCheck", "GMeasure"))
        self.label_33.setText(_translate("BCQualityCheck", "GMean"))
        self.label_34.setText(_translate("BCQualityCheck", "Balance"))
        self.label_35.setText(_translate("BCQualityCheck", "Density"))
        self.groupBox_5.setTitle(_translate("BCQualityCheck", "批量实验数据计算和检查"))
        self.label_8.setText(_translate("BCQualityCheck", "输入文件"))
        self.label_9.setText(_translate("BCQualityCheck", "输出路径"))
        self.pushButton_6.setText(_translate("BCQualityCheck", "浏览"))
        self.pushButton_7.setText(_translate("BCQualityCheck", "浏览"))
        self.pushButton_8.setText(_translate("BCQualityCheck", "输入文件模板"))
        self.pushButton_9.setText(_translate("BCQualityCheck", "预测性能计算"))
        self.pushButton.setText(_translate("BCQualityCheck", "=>预测性能计算"))
        self.pushButton_2.setText(_translate("BCQualityCheck", "<=混淆矩阵反算"))
        self.pushButton_3.setText(_translate("BCQualityCheck", "帮助"))

